import "~/styles/globals.css";

import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";

export const metadata: Metadata = {
	title: "PDF Summarizer",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = Source_Sans_3({
	subsets: ["latin"],
	variable: "--font-sans",
	weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${fontSans.variable} font-sans`}>
			<body>{children}</body>
		</html>
	);
}
